### create new user

POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "you@example.com",
  "password": "tefdfdfst"
}

### Find a particular user with the given id
GET http://localhost:3000/auth/13

### Find all users with the given email
GET http://localhost:3000/auth?email=test@example.com

### Delete a user with the given id 
DELETE http://localhost:3000/auth/9

###Update a user
PATCH http://localhost:3000/auth/12
content-type: application/json

{
  "password": "123456"
}
